export const games = [
    { label: "League of Legends", value: "league_of_legends", image: "/games/logo_lol.jpg" },
    { label: "Valorant", value: "valorant", image: "/games/logo_valorant.jpg" },
    { label: "Fortnite", value: "fortnite", image: "/games/Fortnite.png" },
    { label: "Call of Duty Warzone", value: "call_of_duty_warzone", image: "/games/Call_of_Duty_Warzone.png" },
    { label: "FIFA 23", value: "fifa_23", image: "/games/FIFA_23.png" },
    { label: "League of Legends TFT", value: "tft", image: "/games/logo_tft.jpg" },
    { label: "Brawl Stars", value: "brawl_stars", image: "/games/Brawl_Stars.png" },
    { label: "Clash Royale", value: "clash_royale", image: "/games/Clash_Royale.png" },
    { label: "Clash of Clans", value: "clash_of_clans", image: "/games/Clash_of_Clans.png" },
    { label: "Rocket League", value: "rocket_league", image: "/games/Rocket_League.png" },
    { label: "Overwatch 2", value: "overwatch_2", image: "/games/Overwatch_2.png" },
    { label: "minecraft", value: "minecraft", image: "/games/logo_minecraft.jpg" },
    { label: "Counter-Strike 2", value: "counter_strike_2", image: "/games/Counter-Strike_2.png" },
    { label: "Call of Duty Modern Warfare 2", value: "call_of_duty_mw2", image: "/games/Call_of_Duty_MW2.png" },
    { label: "Apex Legends", value: "apex_legends", image: "/games/Apex_Legends.png" },
    { label: "Rainbow Six Siege", value: "rainbow_six_siege", image: "/games/Rainbow_Six_Siege.png" },
    { label: "FIFA 24", value: "fifa_24", image: "/games/FIFA_24.png" },
    { label: "PUBG", value: "pubg", image: "/games/PUBG.png" },
    { label: "Dota 2", value: "dota_2", image: "/games/Dota_2.png" },
    { label: "Hearthstone", value: "hearthstone", image: "/games/Hearthstone.png" },
    { label: "StarCraft II", value: "starcraft_2", image: "/games/StarCraft_II.png" },
    { label: "World of Warcraft", value: "world_of_warcraft", image: "/games/World_of_Warcraft.png" },
    { label: "Super Smash Bros Ultimate", value: "smash_bros_ultimate", image: "/games/logo_ssb.jpg" },
    { label: "Marvel Rivals", value: "marvel_rivals", image: "/games/marvel_rival.png" },
    { label: "Street Fighter 6", value: "street_fighter_6", image: "/games/Street_Fighter_6.png" },
];