export const valorantRanks = [
    { label: "Iron 1", value: 1, image: "/ranks/Iron_1_Rank.png" },
    { label: "Iron 2", value: 2, image: "/ranks/Iron_2_Rank.png" },
    { label: "Iron 3", value: 3, image: "/ranks/Iron_3_Rank.png" },
    { label: "Bronze 1", value: 4, image: "/ranks/Bronze_1_Rank.png" },
    { label: "Bronze 2", value: 5, image: "/ranks/Bronze_2_Rank.png" },
    { label: "Bronze 3", value: 6, image: "/ranks/Bronze_3_Rank.png" },
    { label: "Silver 1", value: 7, image: "/ranks/Silver_1_Rank.png" },
    { label: "Silver 2", value: 8, image: "/ranks/Silver_2_Rank.png" },
    { label: "Silver 3", value: 9, image: "/ranks/Silver_3_Rank.png" },
    { label: "Gold 1", value: 10, image: "/ranks/Gold_1_Rank.png" },
    { label: "Gold 2", value: 11, image: "/ranks/Gold_2_Rank.png" },
    { label: "Gold 3", value: 12, image: "/ranks/Gold_3_Rank.png" },
    { label: "Platinum 1", value: 13, image: "/ranks/Platinum_1_Rank.png" },
    { label: "Platinum 2", value: 14, image: "/ranks/Platinum_2_Rank.png" },
    { label: "Platinum 3", value: 15, image: "/ranks/Platinum_3_Rank.png" },
    { label: "Diamond 1", value: 16, image: "/ranks/Diamond_1_Rank.png" },
    { label: "Diamond 2", value: 17, image: "/ranks/Diamond_2_Rank.png" },
    { label: "Diamond 3", value: 18, image: "/ranks/Diamond_3_Rank.png" },
    { label: "Ascendant 1", value: 19, image: "/ranks/Ascendant_1_Rank.png" },
    { label: "Ascendant 2", value: 20, image: "/ranks/Ascendant_2_Rank.png" },
    { label: "Ascendant 3", value: 21, image: "/ranks/Ascendant_3_Rank.png" },
    { label: "Immortal 1", value: 22, image: "/ranks/Immortal_1_Rank.png" },
    { label: "Immortal 2", value: 23, image: "/ranks/Immortal_2_Rank.png" },
    { label: "Immortal 3", value: 24, image: "/ranks/Immortal_3_Rank.png" },
];
