version: '3.8'

services:
  frontend:
    build:
      context: ./web_frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    build:
      context: ./api_backend
      dockerfile: Dockerfile

    container_name: backend
